<a href="https://colab.research.google.com/github/utkarsh6174/ML/blob/main/complete_pandas_tutorial_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PANDAS LIBRARY:
USEFUL FOR DATA PROCESSING AND ANALYSIS
PANDAS DATA FRAME :
IS TWO DIMENSIONAL TABULAR DATA STRUCTURE WITH LABELED AXES(ROWS AND COLUMS)

In [ ]:
import  pandas as pd
import numpy as np

from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
#pandas DataFrame
iris_df = pd.DataFrame(iris_dataset.data,columns = iris_dataset.feature_names)
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

Importing the data from a CSV file to a pandas DataFrame

In [ ]:
 # csv file to pandas df
 diabetes_df = pd.read_csv('/content/diabetes.csv')
 type(diabetes_df)
 diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
diabetes_df.shape

(768, 9)

Loading the data from a excel file to a Pandas DataFrame:
pd.read_excel(filepath)
exporting a DataFrame to a csv file

In [ ]:
#iris_df.to_csv('iris.csv')

Exporting the Pandas DataFrame to an excel file:
df.to_excel('file name')

In [ ]:
#create a DataFrame with random values
random_df = pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.790751,0.526334,0.668742,0.604671,0.115934,0.146487,0.854589,0.382609,0.856095,0.730523
1,0.139675,0.837771,0.149406,0.302381,0.222989,0.182563,0.946454,0.652024,0.796570,0.586866
2,0.367082,0.195435,0.791358,0.026248,0.483885,0.449730,0.041440,0.500107,0.279665,0.512361
3,0.772609,0.298129,0.612462,0.979741,0.173440,0.999247,0.407966,0.770162,0.521223,0.522145
4,0.513871,0.624398,0.017081,0.137742,0.484885,0.444434,0.833706,0.448322,0.836178,0.897233

In [ ]:
random_df.shape

(20, 10)

Inspecting a DataFrame

In [ ]:
#finding the number of rows and colums
iris_df.shape

(150, 4)

In [ ]:
#first five rows in a DataFrame
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
# last five rows in a DataFrame
iris_df.tail()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
#informations about the DataFrame
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [ ]:
#find the number of missing value
iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [ ]:
diabetes_df.head()#

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#counting the values based on the labels
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#grouping the values based on the mean
diabetes_df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

Statistical measures

In [ ]:
#count or number of values
iris_df.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
dtype: int64

In [ ]:
 #mean values - column wise
 iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
iris_df.min()
iris_df.max()
iris_df.std()

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

In [ ]:
# all the statistical measures about the DataFrame
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

Manipulating a DataFrame

In [ ]:
# adding a column to a dataframe
#boston_df['Price'] = boston_dataset.target

In [ ]:
#removing a row
iris_df.drop(index = 0,axis  = 0)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[149 rows x 4 columns]

In [ ]:
#iris_df.drop(columns = 'sepal length (cm)'  , axis = 1)

In [ ]:
#locating a row using the index value
iris_df.iloc[2]

sepal length (cm)    4.7
sepal width (cm)     3.2
petal length (cm)    1.3
petal width (cm)     0.2
Name: 2, dtype: float64

In [ ]:
#locating a particular column
iris_df.iloc[:,2]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64

Correlation:
1. positive
2. negative

In [ ]:
iris_df.corr()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.117570,0.871754,0.817941
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126
petal length (cm),0.871754,-0.428440,1.000000,0.962865
petal width (cm),0.817941,-0.366126,0.962865,1.000000